export const dummyUserData = [
    {
        username: 'john_doe',
        email: 'john.doe@example.com',
        address: '123 Main St, Springfield',
        phone: '123-456-7890',
        dob: new Date('1990-05-14'),
        team: 'Team Alpha',
        points: 100,
        status: 'active',
        leftReview: false,
        createdAt: new Date(),
    },
    {
        username: 'jane_smith',
        email: 'jane.smith@example.com',
        address: '456 Elm St, Metropolis',
        phone: '987-654-3210',
        dob: new Date('1985-10-20'),
        team: 'Team Beta',
        points: 150,
        status: 'blocked',
        leftReview: true,
        createdAt: new Date(),
    },
    {
        username: 'bob_jones',
        email: 'bob.jones@example.com',
        address: '789 Oak St, Gotham',
        phone: '555-555-5555',
        dob: new Date('1992-03-07'),
        team: 'Team Gamma',
        points: 50,
        status: 'active',
        leftReview: false,
        createdAt: new Date(),
    },
    {
        username: 'john_doe',
        email: 'john.doe@example.com',
        address: '123 Main St, Springfield',
        phone: '123-456-7890',
        dob: new Date('1990-05-14'),
        team: 'Team Alpha',
        points: 100,
        status: 'active',
        leftReview: false,
        createdAt: new Date(),
    },
    {
        username: 'jane_smith',
        email: 'jane.smith@example.com',
        address: '456 Elm St, Metropolis',
        phone: '987-654-3210',
        dob: new Date('1985-10-20'),
        team: 'Team Beta',
        points: 150,
        status: 'blocked',
        leftReview: true,
        createdAt: new Date(),
    },
    {
        username: 'bob_jones',
        email: 'bob.jones@example.com',
        address: '789 Oak St, Gotham',
        phone: '555-555-5555',
        dob: new Date('1992-03-07'),
        team: 'Team Gamma',
        points: 50,
        status: 'active',
        leftReview: false,
        createdAt: new Date(),
    },
    {
        username: 'john_doe',
        email: 'john.doe@example.com',
        address: '123 Main St, Springfield',
        phone: '123-456-7890',
        dob: new Date('1990-05-14'),
        team: 'Team Alpha',
        points: 100,
        status: 'active',
        leftReview: false,
        createdAt: new Date(),
    },
    {
        username: 'jane_smith',
        email: 'jane.smith@example.com',
        address: '456 Elm St, Metropolis',
        phone: '987-654-3210',
        dob: new Date('1985-10-20'),
        team: 'Team Beta',
        points: 150,
        status: 'blocked',
        leftReview: true,
        createdAt: new Date(),
    },
    {
        username: 'bob_jones',
        email: 'bob.jones@example.com',
        address: '789 Oak St, Gotham',
        phone: '555-555-5555',
        dob: new Date('1992-03-07'),
        team: 'Team Gamma',
        points: 50,
        status: 'active',
        leftReview: false,
        createdAt: new Date(),
    },
];